### ISSUE TITLE
Can´t install plugin

### ISSUE THREAD

**Issue by geraldo** [qgis/QGIS-Hub-Plugin#102]
### What is the bug or the crash?

Installation fails with message "Plugin installation failed: The specified configuration cannot be used."

### Steps to reproduce the issue

Install through "Manage and install plugins..."

### QGIS and Plugin Versions

3.34.12

### Operating System

Ubuntu 22.04

**Comment by ismailsunni** [comment]
@geraldo could you try again without any other plugin installed? Or use a new profile?

**Comment by geraldo** [comment]
Installation does work perfectly on a new profile - and now also does in my default profile with a lots of plugins. I can't reproduce this error right now, so closing.
