### ISSUE TITLE
LAS2DEM utility produces elevation values equal to '0'.

### ISSUE THREAD

**Issue by chuxohl** [qgis/QGIS-Hub-Plugin#95]
### What is the bug or the crash?

I downloaded a LAZ file from TNRIS.org which is the Texas Geographic Information Office. I used the las2dem(file) option and picked the input laz file. I took all the defaults (step 1 and keep class 2). The DEM I got back had a number of linear stripes left in it. When I queried the stripe with the Identify Features tool I got a popup that indicated the value was zero.  I tried changing to a step size of 2 to no avail. Stripes were still present. 

I returned to the layer properties and discovered that the default Classification choice for symbology contained only the values of 'Unclassified' and 'Ground'. Thinking the 'Unclassified' was a problem I filtered them out and reran the process. This tool results in the same exact stripes. 

My instinct suggests the conversion to raster has an issue.  I do not know how to handle this situation. Please advise!

![las2dem](https://github.com/user-attachments/assets/ee7a1ccb-6ace-491b-b2b0-db30e65f08c8)
![las2dem2](https://github.com/user-attachments/assets/bf8f5a72-2c56-4865-8493-d7a402c8c640)

### Steps to reproduce the issue

Download LAZ file
Display in map canvas using browser
Start las2dem(file) and load file
Take defaults
Name output file with .tif extension
Display DEM using single band pseudocolor
Use identify Features tool

### QGIS and Plugin Versions

QGIS 3.38.2
LAStools 2.1.1

### Operating System

Windows 11

**Comment by ismailsunni** [comment]
Hi @chuxohl this is not the correct place to submit QGIS bug report. Please submit it on https://github.com/qgis/QGIS/issues
